### ISSUE TITLE
use file with state=absesnt

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/jenkins-rpc#377]
Anywhere we have a file delete with rm rf needs to be switched to state=absent with the file modue

15:50:12 TASK: [teardown-network-node | Recursive delete of /openstack directory] ****** 
15:50:12 <10.127.101.108> REMOTE_MODULE command rm -rf /openstack/* #USE_SHELL
15:50:12 changed: [node108] => {"changed": true, "cmd": "rm -rf /openstack/*", "delta": "0:00:00.003334", "end": "2015-06-08 15:50:12.252777", "rc": 0, "start": "2015-06-08 15:50:12.249443", "stderr": "", "stdout": "", "warnings": ["Consider using file module with state=absent rather than running rm"]}

**Comment by jpmontez** [comment]
https://groups.google.com/d/msg/ansible-project/hN-lEidIv6E/kyqQL38eRAQJ

DeHaan recommends using "shell" to recursively delete files within a directory.

The `file` module currently does not support wildcard arguments within a provided path. Alternatively, registering the output of a directory listing as input for a recursively deleting for-loop will not work within Ansible; the module works on a per-file basis so, in this scenario, the `state=absent` & `recurse=yes` options are mutually exclusive.
