### ISSUE TITLE
teardown play / task are failing when destroying containers

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/jenkins-rpc#400]
http://jenkins.propter.net/job/nightly-multinode-docker/1919/consoleFull

need to either ignore the failure as the containers do get torndown, or fix and use the lxc module

**Comment by jpmontez** [comment]
[This commit](https://github.com/rcbops/jenkins-rpc/commit/a5dc9153448e211ec60ec594005563b4d2267c3a) should fix this issue.
