### ISSUE TITLE
we need to test holland

### ISSUE THREAD

**Issue by mancdaz** [rcbops/jenkins-rpc#600]
I'm opening this issue here to track the gating work to test holland, that needs to happen now that we've fixed holland in all branches, so that we can close off the [original issue](https://github.com/rcbops/rpc-openstack/issues/1121) in rpc-openstack where we fixed holland.

**Comment by git-harry** [comment]
This has been addressed by https://github.com/rcbops/jenkins-rpc/commit/8754e72dde40400dac1bd0aafa62d24dce743cf6
